#!/bin/sh
set -eu

if git status --short | grep --quiet '^MM'; then
  printf '%s\n' "ERROR: Some staged files have unstaged changes" >&2
  exit 1;
fi

# https://github.com/lint-staged/lint-staged
pnpm lint-staged

git update-index --again
